CREATE DATABASE QLCLBSACH;
USE QLCLBSACH;

CREATE TABLE QUYENDANGNHAP
(MAQUYENDN NVARCHAR(10) PRIMARY KEY,
QUYEN NVARCHAR(10) NOT NULL)

CREATE TABLE THANHVIEN
(MATV INT PRIMARY KEY,
TENTV NVARCHAR(100) NOT NULL,
MATKHAU NVARCHAR(50) NOT NULL,
DIACHI NVARCHAR(200) NOT NULL,
EMAIL NVARCHAR(100) NOT NULL,
MAQUYENDN NVARCHAR(10) REFERENCES QUYENDANGNHAP);

CREATE TABLE TACGIA
(MATG NVARCHAR(10) PRIMARY KEY,
TENTG NVARCHAR(100) NOT NULL);

CREATE TABLE THELOAI
(MATL NVARCHAR(10) PRIMARY KEY,
TENTL NVARCHAR(20) NOT NULL);

CREATE TABLE NXB
(MANXB NVARCHAR(10) PRIMARY KEY,
TENNXB NVARCHAR(100) NOT NULL);

CREATE TABLE SACH
(MASACH NVARCHAR(10) PRIMARY KEY,
TENSACH NVARCHAR(100) NOT NULL,
MATG NVARCHAR(10) NOT NULL REFERENCES TACGIA,
MATL NVARCHAR(10) NOT NULL REFERENCES THELOAI,
MANXB NVARCHAR(10) NOT NULL REFERENCES NXB,
NAMXB INT NOT NULL,
NGONNGU NVARCHAR(50) NOT NULL);

 INSERT INTO QUYENDANGNHAP VALUES('ADMIN','Admin');
INSERT INTO QUYENDANGNHAP values('THANHVIEN','Thành viên');

INSERT INTO THANHVIEN VALUES (1,'ADMIN','admin','Thai Binh','email','ADMIN');

insert into TACGIA values ('TG01','Dale Carnegie');
insert into THELOAI values('TL01','Sach Tu Duy');
insert into NXB values('NXB1','Tri Viet');
insert into SACH values('S01','Dac Nhan Tam','TG01','TL01','NXB1',2016,'Tieng Viet');*/
